//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fosol.Diagnostics.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fosol.Diagnostics.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &quot;{0}&quot; must be a valid type..
        /// </summary>
        internal static string Exception_Argument_Type_Invalid {
            get {
                return ResourceManager.GetString("Exception_Argument_Type_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &quot;{0}&quot; must be an assignable to type &quot;{1}&quot;..
        /// </summary>
        internal static string Exception_Argument_Type_NotAssignable {
            get {
                return ResourceManager.GetString("Exception_Argument_Type_NotAssignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create a new instance of the filter &quot;{0}&quot;..
        /// </summary>
        internal static string Exception_Configuration_Filter_Failed {
            get {
                return ResourceManager.GetString("Exception_Configuration_Filter_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create a new instance of the listener &quot;{0}&quot;..
        /// </summary>
        internal static string Exception_Configuration_Listener_Failed {
            get {
                return ResourceManager.GetString("Exception_Configuration_Listener_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting &quot;{0}&quot; is required..
        /// </summary>
        internal static string Exception_Configuration_Setting_Required {
            get {
                return ResourceManager.GetString("Exception_Configuration_Setting_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting &quot;{0}&quot; has an invalid value..
        /// </summary>
        internal static string Exception_Configuration_Setting_Value_Invalid {
            get {
                return ResourceManager.GetString("Exception_Configuration_Setting_Value_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The TraceSettingAttribute &quot;{0}&quot; requires the ConverterType property value to be set when applied to constructors..
        /// </summary>
        internal static string Exception_Setting_Attribute_Missing_ConverterType {
            get {
                return ResourceManager.GetString("Exception_Setting_Attribute_Missing_ConverterType", resourceCulture);
            }
        }
    }
}
