//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fosol.Diagnostics.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fosol.Diagnostics.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{0}&quot; configuration argument &quot;{1}&quot; failed to convert to type &quot;{2}&quot;..
        /// </summary>
        internal static string Configuration_Exception_Argument_Conversion_Failed {
            get {
                return ResourceManager.GetString("Configuration_Exception_Argument_Conversion_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{0}&quot; configuration argument &quot;{1}&quot; has an invalid converter type &quot;{2}&quot;..
        /// </summary>
        internal static string Configuration_Exception_Argument_Converter_Invalid {
            get {
                return ResourceManager.GetString("Configuration_Exception_Argument_Converter_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{0}&quot; configuration argument &quot;{1}&quot; has an invalid type &quot;{2}&quot;..
        /// </summary>
        internal static string Configuration_Exception_Argument_Type_Invalid {
            get {
                return ResourceManager.GetString("Configuration_Exception_Argument_Type_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{0}&quot; assembly is invalid..
        /// </summary>
        internal static string Configuration_Exception_Assembly_Is_Invalid {
            get {
                return ResourceManager.GetString("Configuration_Exception_Assembly_Is_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{0}&quot; attribute is required..
        /// </summary>
        internal static string Configuration_Exception_Attribute_Required {
            get {
                return ResourceManager.GetString("Configuration_Exception_Attribute_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{0}&quot; filter initialize values are invalid..
        /// </summary>
        internal static string Configuration_Exception_Filter_Initialize_Invalid {
            get {
                return ResourceManager.GetString("Configuration_Exception_Filter_Initialize_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{0}&quot; filter type &quot;{1}&quot; is not valid..
        /// </summary>
        internal static string Configuration_Exception_Filter_Type_Invalid {
            get {
                return ResourceManager.GetString("Configuration_Exception_Filter_Type_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{0}&quot; keyword already exists..
        /// </summary>
        internal static string Configuration_Exception_Keyword_Already_Exists {
            get {
                return ResourceManager.GetString("Configuration_Exception_Keyword_Already_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{0}&quot; keyword requires the &quot;{1}&quot; attribute..
        /// </summary>
        internal static string Configuration_Exception_Keyword_Attribute_Required {
            get {
                return ResourceManager.GetString("Configuration_Exception_Keyword_Attribute_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{0}&quot; keyword does not exist..
        /// </summary>
        internal static string Configuration_Exception_Keyword_Does_Not_Exist {
            get {
                return ResourceManager.GetString("Configuration_Exception_Keyword_Does_Not_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{0}&quot; keyword is not valid..
        /// </summary>
        internal static string Configuration_Exception_Keyword_Is_Not_Valid {
            get {
                return ResourceManager.GetString("Configuration_Exception_Keyword_Is_Not_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{0}&quot; listener arguments are invalid..
        /// </summary>
        internal static string Configuration_Exception_Listener_Arguments_Invalid {
            get {
                return ResourceManager.GetString("Configuration_Exception_Listener_Arguments_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{0}&quot; listener reference cannot include additional properties..
        /// </summary>
        internal static string Configuration_Exception_Listener_Reference_Invalid_Properties {
            get {
                return ResourceManager.GetString("Configuration_Exception_Listener_Reference_Invalid_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{0}&quot; listener reference must point to an existing shared listener..
        /// </summary>
        internal static string Configuration_Exception_Listener_Reference_Must_Exist {
            get {
                return ResourceManager.GetString("Configuration_Exception_Listener_Reference_Must_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{0}&quot; listener type &quot;{1}&quot; is not valid..
        /// </summary>
        internal static string Configuration_Exception_Listener_Type_Invalid {
            get {
                return ResourceManager.GetString("Configuration_Exception_Listener_Type_Invalid", resourceCulture);
            }
        }
    }
}
